name: Docker Image CI

on:
  push:
    branches: 
    - main

jobs:

  login:
      runs-on: ubuntu-latest
      steps:
      -  name: login in docker hub
         uses: docker/login-action@v3.3.0
         with: 
          username: ${{vars.USERNAME}}
          password: ${{secrets.ACCESS_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Build docker image
      run: docker build . --file Dockerfile --tag cloudsystemen:latest
    - name: Publish
      run: docker push cloudsystemen:latest 

  

    

    
